version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./server
    ports:
      - "5000:5000"
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
